auto_save: True
display_label_popup: true
store_data: true
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

flags: null
label_flags: null
labels: {石英,燧石,微斜长石,正长石,条纹长石,斜长石,泥岩岩屑,砂岩岩屑,碳酸盐岩岩屑,石英岩岩屑,片麻岩岩屑,千枚岩岩屑,片岩岩屑,
          花岗岩岩屑,安山岩岩屑,玄武岩岩屑,酸性喷出岩岩屑,火山碎屑岩岩屑,黑云母,白云母,绿泥石,重矿物,泥质,黄铁矿,菱铁矿,方解石,
          白云石,铁方解石,铁白云石,高岭石,高变岩岩屑,泥板岩岩屑,隐晶岩屑,其它,高变岩屑,板岩屑,喷出岩屑,泥板岩屑,变质砂岩屑,变质岩屑}
file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: auto  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: null

shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0]  # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  create_point: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  add_point_to_edge: Ctrl+C
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P

  generate_polygon: null
  remove: null

  Pimage_contrast: null
  Light_balance: null
  Smooth_denoising: null
  auto_recognition: null
  auto_segmentation: null
  layer_contrast: null
  Generate_report: null

server:
  ip: 127.0.0.1
  port: 8333