granule:
  其它: null
  千枚岩岩屑:
    成分特征:
    - 无
    - 粘土质、粉砂质和一部分中基性火山岩与火山碎屑岩经低级变质作用形成。粘土矿物已经全部重结晶形成绢云母、雏晶黑云母和数量较少的绿泥石等片状矿物
    构造特征:
    - 千枚状构造、显微鳞片变晶结构
    - 无
  安山岩岩屑:
    成分特征:
    - 无
    - 主要为中性斜长石（45%-85%）
    结构特征:
    - 斑状结构,交织结构
    - 无
    - 粒间结构
  微斜长石:
    其他:
    - 无
    双晶特征:
    - 无
    - 格子双晶
    干涉色:
    - 无
    - 一级灰白
    消光:
    - 无
    - 斜消光
    解理:
    - 无
    - 两组完全解理
    风化特征:
    - 无
    - 表面无色透明
    - 表面浑浊、浅土褐色
  斜长石:
    双晶特征:
    - 无
    - 聚片双晶
    干涉色:
    - 无
    - 一级灰、一级灰白、一级黄白
    晶形:
    - 无
    - 板状、叶片状、等轴粒状
    解理:
    - 无
    - 两组完全解理
    颜色:
    - 无
    - 部分绢云母化,表面浑浊
    - 表面无色透明
  方解石: null
  条纹长石:
    晶形:
    - 无
    - 正交光下具条纹结构
    组成特征:
    - 无
    - 钾长石（主晶）和纳质长石（客晶）
    风化特征:
    - 无
    - 表面无色透明
    - 表面浑浊,浅土褐色
  正长石:
    其他:
    - 无
    双晶特征:
    - 卡斯巴双晶
    - 无
    干涉色:
    - 无
    - 一级灰白
    - 一级灰
    晶形:
    - 无
    - 板状、粒状
    风化特征:
    - 无
    - 表面无色透明
    - 具高岭土化,浅土褐色
  泥岩岩屑:
    结构特征:
    - 无
    - 显微层理构造
    镜下特征:
    - 无
    - 表面污浊,呈土褐色,常有黑色碳质混入物,正交偏光下由鳞片状绢云母及粘土矿物组成。
  泥板岩岩屑: null
  泥质: null
  火山碎屑岩岩屑:
    成分特征:
    - 无
    - 火山喷发的各种岩屑、晶屑、玻屑等
    类型:
    - 无
    - 集块岩
    - 火山角砾岩
    - 凝灰岩
    - 熔结类岩石
  燧石:
    其他:
    - 无
    - 纤维状、放射状集合体
    双晶特征:
    - 无
    干涉色:
    - 无
    - 一级灰白
    消光:
    - 平行消光
    - 无
    解理:
    - 无
    风化特征:
    - 不易风化、表面无色透明
    - 无
  片岩岩屑:
    成分特征:
    - 无
    - 主要由片状矿物（黑云母、绿泥石等）、柱状矿物（透闪石、普通角闪石等）+粒状矿物（长石、石英等）组成，片状+柱状矿物含量≥30%
    构造特征:
    - 无
    - 鳞片变晶结构，片理构造。
  片麻岩岩屑:
    成分特征:
    - 无
    - 长石和石英含量>70%，其中的长石含量>25%，其他为云母、角闪石等
    构造特征:
    - 无
    - 片麻状结构,云母、角闪石等多呈不连续的定向分布。
  玄武岩岩屑:
    成分特征:
    - 无
    - 主要为基性斜长石、辉石以及橄榄石
    结构特征:
    - 无
    - 斑状结构,间粒结构
    - 间隐结构
    - 填间结构
    - 球粒结构
    - 气孔构造
    - 杏仁构造
  白云母:
    干涉色:
    - 无
    - 具鲜艳的二至三级干涉色
    晶形:
    - 无
    - 片状
    消光:
    - 无
    - 近平等消光
    突起:
    - 无
    - 闪突起明显
    解理:
    - 无
    - 一组完全解理
    颜色:
    - 无
    - 单偏下无色
  白云石: null
  石英:
    双晶特征:
    - 无
    干涉色:
    - 一级灰、一级灰白、一级黄白
    - 无
    消光:
    - 无
    - 波状消光(受应力作用石英), 平均消光
    解理:
    - 无
    风化特征:
    - 不易风化、表面无色透明
    - 无
  石英岩岩屑:
    成分特征:
    - 无
    - 石英>90%，其他为长石云母等
    构造特征:
    - 无
    - 块状结构,石英具有拉长定向排列特征
  砂岩岩屑:
    结构特征:
    - 无
    - 砂状结构
    镜下特征:
    - 无
    - 石英、长石、岩屑、填隙物等清晰可辨，无变质现象
  碳酸盐岩岩屑:
    成分特征:
    - 无
    - 主要由白云岩岩屑和灰岩岩屑
  绿泥石:
    干涉色:
    - 无
    - 一级
    - 靛蓝等异常干涉色
    晶形:
    - 无
    - 片状
    - 鳞片状、玫瑰花形集合体产出
    消光:
    - 无
    - 近平等消光
    解理:
    - 无
    - 一组完全解理
    颜色:
    - 无
    - 深灰色
    - 浅绿色
    - 绿黑色
  花岗岩岩屑:
    成分特征:
    - 无
    - 主要由石英、长石组成（含量大于85%）
    结构特征:
    - 无
    - 花岗结构
    - 似斑状结构
    - 文象结构
    - 蠕虫结构
  菱铁矿: null
  酸性喷出岩岩屑:
    成分特征:
    - 无
    - 石英斑晶、斑晶和基质中含有碱性长石（流纹岩）、斜长石（英安岩）
    类型:
    - 无
    - 流纹岩
    - 英安岩
    结构特征:
    - 无
    - 斑状结构,流纹构造
    - 隐晶质结构
    - 霏细结构
    - 球粒结构
  重矿物:
    特征:
    - 无
    - 颗粒小粉砂级，凸起高
  铁方解石: null
  铁白云石: null
  隐晶岩屑: null
  高变岩岩屑: null
  高岭石: null
  黄铁矿: null
  黑云母:
    多色吸收:
    - 无
    - 强
    - 弱
    晶形:
    - 无
    - 片状
    消光:
    - 近平行消光
    - 无
    解理:
    - 极完全一组解理
    - 无
    颜色:
    - 无
    - 黑
    - 深褐色
    - 绿色
  默认名: null
  高变岩屑: null
  板岩屑: null
  喷出岩屑: null
  泥板岩屑: null
  变质砂岩屑: null
  变质岩屑: null
